### ISSUE TITLE
Slice not working properly

### ISSUE THREAD

**Issue by alexandrevicenzi** [alexandrevicenzi/gistfy#19]
If i set slice=1:3, it shows one more line.

For example: [http://www.gistfy.com/github/ButecoOpenSource/exemplos/exemplos_python/pygtk/pygtk-form.py?slice=35:43](http://www.gistfy.com/github/ButecoOpenSource/exemplos/exemplos_python/pygtk/pygtk-form.py?slice=35:43&type=html)

**Comment by marcosps** [comment]
Please fix this annoying bug.
