### ISSUE TITLE
invalid character is shown when copying code and pasting it somewhere

### ISSUE THREAD

**Issue by JerryGoyal** [alexandrevicenzi/gistfy#23]
when I copy code from gistfy and paste it somewhere an extra character gets pasted before each line.

**Comment by alexandrevicenzi** [comment]
Hi @JerryGoyal,

What is your OS and browser version?

**Comment by JerryGoyal** [comment]
I'm using chrome 45 on Windows 10

On 28/09/2015, Alexandre Vicenzi <notifications@github.com> wrote:
> Hi @JerryGoyal,
>
> What is your OS and browser version?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexandrevicenzi/gistfy/issues/23#issuecomment-143600534


-- 
Gourav Goyal
