### ISSUE TITLE
Invalid Url for bika.lims git repo

### ISSUE THREAD

**Issue by trendsetter37** [alexandrevicenzi/gistfy#27]
Using [Gistfy](https://gistfy.com) I am getting a Invalid Url error for a valid repository file.

Reproduce using [this](https://github.com/bikalabs/bika.lims/blob/master/bika/lims/browser/analysisrequest/analysisrequests.py) file.

**Comment by alexandrevicenzi** [comment]
I will take a look. I can reproduce this here.

**Comment by trendsetter37** [comment]
I can take a closer look later tonight as well but could it be somewhere in here?

L#263
`gistfy.js`
```javascript
if (host === 'github') {
    htmlUrl =  util.format('https://github.com/%s/%s/blob/%s/%s', user, repo, branch, path);
    rawUrl =  util.format('https://raw.githubusercontent.com/%s/%s/%s/%s', user, repo, branch, path);
    repoUrl = util.format('https://github.com/%s/%s', user, repo);
```

**Comment by alexandrevicenzi** [comment]
@trendsetter37 it's fixed.

Thanks.

**Comment by trendsetter37** [comment]
More specifically I think it has to do with any url that has a `.` in the url other than at the end delimiting the file type.

#### Invalid url (according to Gistfy but valid repo files)
---
https://github.com/trendsetter37/bika.lims/blob/master/setup.py
https://github.com/bikalabs/bika.lims/blob/master/bika/lims/tests/test_ARImport.py

#### Valid url (minus extra `.`)
---
https://github.com/cambecc/earth/blob/master/public/test/micro-test.html

**Comment by alexandrevicenzi** [comment]
Yes, there's a regex to validate urls, and it wasn't accepting special chars in repository name.

**Comment by trendsetter37** [comment]
Thanks @alexandrevicenzi
