### ISSUE TITLE
Bind to public IP?

### ISSUE THREAD

**Issue by k0nsl** [alexandrevicenzi/gistfy#29]
What is the parameter for making `gistfy` bind to public IP, or one that I can specify manually? As far as I can recall, this used to be possible at one point. However, it's been some five months since I used it and I can't remember how I got it working.
At the moment it will only bind to `127.0.0.1`.

**Comment by k0nsl** [comment]
I found it. It was of course in `./src` :D

**Comment by alexandrevicenzi** [comment]
@k0nsl I think there's no doc for this.

But you can aways run `node src/gistfy.js --port=8080 --host='0.0.0.0'` so it will bind any IP.
